language: dart
sudo: false
dart:
  - stable
  - dev
with_content_shell: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./tool/travis.sh

# dart_task:
#  - dartfmt: -n templates # can't be used jointly with `with_content_shell`
